"""A-share multi-period stock tracker toolkit."""

from __future__ import annotations

from src.stock_tracker.engine import StockTrackerEngine
from src.stock_tracker.models import (
    ChipHolderItem,
    ChipSnapshot,
    ConceptSnapshot,
    ConceptStrength,
    ConsensusSnapshot,
    CrossDayDiff,
    DivergenceMark,
    EventItem,
    EventSnapshot,
    IndicatorBar,
    IndicatorSeries,
    MarketSentimentSnapshot,
    PeriodMetrics,
    PeriodSignals,
    RiskMetrics,
    SectorPeriodMetric,
    SectorStrength,
    SignalState,
    SignalType,
    SignalValue,
    SymbolSnapshot,
    TrackerConfig,
    TrackerSettings,
    TrackerSnapshot,
    TrackerThresholds,
    ValuationSnapshot,
)
from src.stock_tracker.indicators import (
    compute_bollinger,
    compute_kdj,
    compute_macd,
    find_divergence,
    find_swing_points,
)
from src.stock_tracker.risk import compute_atr, compute_beta, compute_max_drawdown
from src.stock_tracker.signals import (
    BollingerPctBDetector,
    BollingerSqueezeDetector,
    BreakoutDetector,
    DivergenceDetector,
    KdjDetector,
    MaAlignmentDetector,
    MacdDetector,
    RSIDetector,
    VolumeSpikeDetector,
    compute_mas,
    compute_rsi,
    get_detector,
    get_detector_meta,
    list_detector_meta,
    list_detector_names,
    register_detector,
)
from src.stock_tracker.store import TrackerStore

__all__ = [
    "BollingerPctBDetector",
    "BollingerSqueezeDetector",
    "BreakoutDetector",
    "ChipHolderItem",
    "ChipSnapshot",
    "ConceptSnapshot",
    "ConceptStrength",
    "ConsensusSnapshot",
    "CrossDayDiff",
    "DivergenceDetector",
    "DivergenceMark",
    "EventItem",
    "EventSnapshot",
    "IndicatorBar",
    "IndicatorSeries",
    "KdjDetector",
    "MaAlignmentDetector",
    "MacdDetector",
    "MarketSentimentSnapshot",
    "PeriodMetrics",
    "PeriodSignals",
    "RSIDetector",
    "RiskMetrics",
    "SectorPeriodMetric",
    "SectorStrength",
    "SignalState",
    "SignalType",
    "SignalValue",
    "StockTrackerEngine",
    "SymbolSnapshot",
    "TrackerConfig",
    "TrackerSettings",
    "TrackerSnapshot",
    "TrackerStore",
    "TrackerThresholds",
    "ValuationSnapshot",
    "VolumeSpikeDetector",
    "compute_atr",
    "compute_beta",
    "compute_bollinger",
    "compute_kdj",
    "compute_macd",
    "compute_mas",
    "compute_max_drawdown",
    "compute_rsi",
    "find_divergence",
    "find_swing_points",
    "get_detector",
    "get_detector_meta",
    "list_detector_meta",
    "list_detector_names",
    "register_detector",
]
